### ISSUE TITLE
Monsters

### ISSUE THREAD

**Issue by Resoluciones** [Programie/TalkingMobs#3]
Hi!  I think monsters are not reacting when they are being hit.

Animals work perfect, but aggresive monsters don't.  Maybe you can take a look at it if you have time.

Thanks!!!

**Comment by Programie** [comment]
Do you see any "No messages for event xxx of mob yyy defined!" log messages?

**Comment by Resoluciones** [comment]
Sorry!!! It's my mistake!! I just realized I reset the config and some mobs were not present in the original messages file.  I am really sorry, there is no bug, it's my fault!!!

**Comment by Programie** [comment]
No problem, could have also happen to me. 😄

Resetting the config (i.e. removing the files) should trigger regenerating the file. So if you remove the messages.yaml, the plugin should write the default one to disk once the plugin is loaded the next time. Otherwise this is a bug and not your fault.

Or maybe do you mean, you tested it with mobs which aren't in the messages.yaml by default (for example, hitting a zombie or a creeper should show a message)? I didn't had the time and creativity to write down messages for all currently existing mobs, so not all mobs have messages by default. If you have some good messages and want to share them, feel free to do so. 😉

**Comment by Resoluciones** [comment]
Yes, I installed it in a different server and I forgot to update the messages.yml, I was very silly, sorry.

mmm... the messages I have are specific for the server, they won't be good for general servers (as they won't have sense in a normal server)!.

**Comment by Programie** [comment]
Oh OK, so this is not an issue with the plugin and I can close the issue.
